### ISSUE TITLE
DockPane Simple example in VB.NET

### ISSUE THREAD

**Issue by tchapin** [Esri/arcgis-pro-sdk-community-samples#15]
I'm trying to convert the DockpaneSimple sample to VB.NET.  Not able to compile due to 2 issues in BookmarkDockpaneViewModel.cs:
1) The line 82
_retrieveMapsCommand = new RelayCommand(() => RetrieveMaps(), () => true);
converted to 
_retrieveMapsCommand = New RelayCommand(Function() RetrieveMaps(), Function() True)
The compiler is complaining that the expression RetrieveMaps() does not produce a value. RetrieveMaps() is a sub, so it doesn't return a value.

2) The line 96
ProjectItemsChangedEvent.Subscribe(OnProjectCollectionChanged, false);
converted to
ProjectItemsChangedEvent.Subscribe(OnProjectCollectionChanged, False)
The compiler is complaining that an argument was not specified for parameter 'args' of Private Sub OnProjectCollectionChanged.

**Comment by arcgisprosdk** [comment]
To check this out I created a sample Dockpane app and added a button and the subscription.  I used Visual Basic intellisense to give me the syntax.  
In regards to your item 1) this code snippet worked for me:
```vb  
  Private _cmdExit As ICommand

  Protected Sub New()
    _cmdExit = new RelayCommand(AddressOf Execute, AddressOf CanExecute)
  End Sub

  Private Function CanExecute() As Boolean
    Return True
  End Function

  Private Sub Execute(obj As Object)
    MessageBox.Show("Button works!")
  End Sub
  
  Public ReadOnly Property CmdExit As ICommand
    Get
      Return _cmdExit
    End Get
  End Property
```  
Regarding item 2) this worked for me:
```vb

  Protected Sub New()
    ProjectItemsChangedEvent.Subscribe(AddressOf Action)
  End Sub

  Private Sub Action(eventArgs As ProjectItemsChangedEventArgs)
    MessageBox.Show(eventArgs.ProjectItem.Type)
  End Sub
```
