### ISSUE TITLE
How to create an xaml map (CaliforniaStartPage)?

### ISSUE THREAD

**Issue by orossini** [Esri/arcgis-pro-sdk-community-samples#18]
In the CaliforniaStartPage sample (StartPage Samples), the California map is described in xaml (in CaliforniaCounties.xaml).
How to convert an existing feature to xaml polyline path  easily?

**Comment by orossini** [comment]
I finally found out how to create the map:
1. Create a map in ArcGIS Pro. 
2. Create a layout of the map in Pro. 
3. Save the layout as a svg file from Pro
4. From there you can open the svg file and get the geometry to paste it in the xaml file or you can go to the next step (easier)
5. Open the svg file in Inkscape (free vector drawing app) 
6. Save it as xaml
7. Add the resulting xaml file in your Visual Studio project, and update it accordingly (make it a UserControl, etc..)

Hope this helps anyone interested in doing that.

Great sample by the way. Thanks to Esri dev team

**Comment by arcgisprosdk** [comment]
Thanks for doc'ing this. I am sure others will find this useful

**Comment by geoholix** [comment]
very useful, many thanks @orossini
