### ISSUE TITLE
It works when license pointing to AGOL, but once I change to my local portal, it doesn't work.

### ISSUE THREAD

**Issue by BingZH** [Esri/arcgis-pro-sdk-community-samples#20]
Hi Esri,
Regarding "ShowLicense" sample.
When I am using local portal for pro licensing server, the response of /sharing/rest/portals/self?f=json doesn't include "appInfo" and "user" section which causes the process fails.
Regards,
Bing

**Comment by Wolf-K** [comment]
Hi Bing,
 I am not sure about the differences in API between AGOL and Portal, however, I think your question would be best asked in the 'Portal for ArcGIS' forum on GeoNet:
[https://geonet.esri.com/community/gis/web-gis/portal-for-arcgis](https://geonet.esri.com/community/gis/web-gis/portal-for-arcgis)

Thanks,
Wolf
