### ISSUE TITLE
Markdown syntax not generating rendered content

### ISSUE THREAD

**Issue by doneill** [Esri/arcgis-pro-sdk-community-samples#21]
The markdown content does not seem to be rendering properly.  

## README.md
- Headers are not rendering

![headers](https://cloud.githubusercontent.com/assets/1308001/24209091/825ffa8a-0ee2-11e7-95d6-5f15a5a8d0f7.png)

- Tags are showing

![tags](https://cloud.githubusercontent.com/assets/1308001/24209139/b28bb01e-0ee2-11e7-85c8-1ac8d75a6dbd.png)

This occurs on wiki pages as well.  

## ProGuide-Contribute-Samples

![wiki](https://cloud.githubusercontent.com/assets/1308001/24209228/edee8abe-0ee2-11e7-86f3-b99416632e16.png)

**Comment by Wolf-K** [comment]
Thanks for making us aware of this.  It appears that a GitHub server software update broke this everywhere.  We are looking into this.

[https://github.com/jekyll/jekyll/issues/4456](https://github.com/jekyll/jekyll/issues/4456)

**Comment by Wolf-K** [comment]
Fixed the issues
