### ISSUE TITLE
Async Databinding using ArcGIS Pro SDK and MVVM?

### ISSUE THREAD

**Issue by PhanindraGIS1in** [Esri/arcgis-pro-sdk-community-samples#28]
Hello,

How can we bind data to datagrid (In dockpane) using Async programing in ArcGIS Pro SDk and MVVM as one of my process will take lot of time.

Please let me know if you can have any ideas or samples.

Thank you,

Regards,
Phanindra

**Comment by Wolf-K** [comment]
Sorry about the late reply, however, there are a few samples that implement datagrid with observable collections that are updated by asynchronous processes.  For example: [IdentifyWindow](https://github.com/Esri/arcgis-pro-sdk-community-samples/tree/master/Map-Exploration/IdentifyWindow).  Just remember to use BindingOperations.EnableCollectionSynchronization (...) after you first create your observable collection.
