### ISSUE TITLE
Reference component from another add-in

### ISSUE THREAD

**Issue by eczajk1** [Esri/arcgis-pro-sdk-community-samples#37]
Is it possible to add a component from another add-in to my current add-in project?

Like, if I want to create a new add-in that leverages functionality (a button, for example) that exists in another add-in that was created previously, how can that be done?

**Comment by Wolf-K** [comment]
You can check out this guide: [Reusing Pro Commands](https://github.com/Esri/arcgis-pro-sdk/wiki/ProGuide-Reusing-Pro-Commands) this will work for Pro commands and anything available in any add-in that is loaded by ArcGIS Pro.

**Comment by eczajk1** [comment]
Thanks. I had gotten a little confused by [this blog post](https://www.esri.com/arcgis-blog/products/arcgis-pro/uncategorized/manage-arcgis-pro-add-in-loading/) which is demonstrating how `config.daml` can be used to insert add-in components onto the ribbon of another add-in. But this seems backwards to what I was trying to do.

Ultimately, I was able to determine that components from another add-in *can* be added to your add-in project by simply adding the project as a dependency and referencing the correct `refID`. [This article](https://github.com/Esri/arcgis-pro-sdk/wiki/ProConcepts-Advanced-Topics) has some other relevant information.
