### ISSUE TITLE
Arcgis Pro LineOffset not working

### ISSUE THREAD

**Issue by ikbalyasar** [Esri/arcgis-pro-sdk-community-samples#38]
Although I have defined offset on lines in ArcGIS Pro environment, line offset definitions are not reflected in the style file resulting from the vector tile package produced.
I manually added “line-offset”: 2 parameter to each layer in the resulting style file (root.json).
When I draw the new style that I have prepared using the api, it does not use the line-offset parameter.  The lines continue to intertwine on small scales.

Do you have a solution?

**Comment by Wolf-K** [comment]
It would be best if you could post your question on [Geonet](https://community.esri.com/) under 'ArcGIS Pro SDK' since Geonet is monitored and replied to by the API developers.  I would also suggest to include a small code snippet showing the API manipulation you are having the problem with.
