### ISSUE TITLE
AddIn info

### ISSUE THREAD

**Issue by sindizzy** [Esri/arcgis-pro-sdk-community-samples#44]
There used to a great helper file to programmatically get info about your own Addin here https://github.com/Esri/arcgis-pro-sdk-community-samples/tree/master/Content/AddInInfoManager

I no longer see that available? Has some other functionality take its place?

**Comment by Wolf-K** [comment]
You should be able to get to previous releases and download the source .zip file to get to that file.  I think the 3.0 version had some issues which are explained here: https://community.esri.com/t5/arcgis-pro-sdk-questions/get-addin-info-pro-3-0/m-p/1191638
