### ISSUE TITLE
Installing plugin datasource breaks arcpy

### ISSUE THREAD

**Issue by jsd290** [Esri/arcgis-pro-sdk-community-samples#51]
See thread here:
https://community.esri.com/t5/python-questions/running-arcpy-script-from-powershell-after/td-p/1261897/page/3

Steps to reproduce: 
1) build and install ProDataReader sln
2) in python shell, run arcpy.CreateFileGDB_management(dir, name)

unhandled exception

**Comment by Wolf-K** [comment]
This is related to this issue: 
https://community.esri.com/t5/python-questions/running-arcpy-script-from-powershell-after/m-p/1322400#M68482
A comprehensive fix is forthcoming in 3.2.
