### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by cynthiajoycebr** [Esri/arcgis-pro-sdk-community-samples#52]
Not so much an issue, as a request: how difficult would it be to alter the Animation From Path sample to be able to follow a 3D polyline, meaning, shift the camera at each keyframe to take into account the Z dimension of the line?  If the sample can't be readily edited to incorporate this, some guidance on how to do this would be most helpful.  Thank you.

**Comment by deepinderdeol** [comment]
It looks like AnimationFromPath sample already supports 3D line features, and the generated keyframes are z-aware. See code for the following two functions in CreateAnimationFromPath.cs:

- CreatePointAlongSegment( )
- CreatePointAlongArc( )

**Comment by Wolf-K** [comment]
These questions are best asked here:  https://community.esri.com/t5/arcgis-pro-sdk-questions/bd-p/arcgis-pro-sdk-questions
