### ISSUE TITLE
"System.__ComObject" returned instead of data for AREA_OF_USE property in CoordinateSystemPicker add-in

### ISSUE THREAD

**Issue by ArunachalamMak** [Esri/arcgis-pro-sdk-community-samples#54]
I encountered an issue while using the CoordinateSystemPicker add-in, where the AREA_OF_USE property returns "System.__ComObject" instead of the expected data. This behavior is unexpected and same for any available Coordinate Systems.

![image](https://github.com/Esri/arcgis-pro-sdk-community-samples/assets/32218791/d29d33ff-e107-429b-a190-e52e3af6fb11)

**Comment by cmac3095** [comment]
thanks. Looks like the issue is with the `CoordinateSystemsDetailsControl`

**Comment by cmac3095** [comment]
this is fixed in 3.3. thanks again.

**Comment by ArunachalamMak** [comment]
Thank you, Charlie!
